server:
  port: 8085
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: 'https://github.com/santoshkumarmehta/microservice-config-service'
          clone-on-start: true
          default-label: main
          skipSslValidation: true
